### ISSUE TITLE
I need your help!

### ISSUE THREAD

**Issue by marambola** [mangusta86/android_kernel_huawei_k3v2oem1#1]
Hello! I have Honor 3, proccesor K3V2.
What I must write in:
TARGET_CPU_ABI := 
TARGET_CPU_ABI2 := 
TARGET_ARCH := 
TARGET_ARCH_VARIANT := 
TARGET_ARCH_VARIANT_CPU :=
TARGET_BOARD_PLATFORM := 
TARGET_SOC :=
?

**Comment by mangusta86** [comment]
this is the kernel section and that's not an issue...
By the way just copy on the device section my settings for hwu9508
